### PR TITLE
Support for L6, L7 and L8

### PR DESCRIPTION
**Pull request by npostman**
Updated this package to add support for latest Laravel versions.
Has been tested on L6.20.23, L7.30.4 and L8.37.0

Guess it breaks on L5.x, but that has been EOL for quite some time.

### CODE REVIEW

**Comment by npostman** [comment]
@dwightwatson Any chance you can review and merge this PR?

**Comment by dwightwatson** [comment]
Sorry, I must have missed this earlier.

Unfortunately I'm really not sure I can merge this - there's a lot of changes to functionality, and without tests (which I know is my fault) there's no confidence that this code will continue to work as expected.

If it's just PHP 8/Laravel 6+ support you want I'm happy to adjust the constraints to make it installable on those versions.

**Comment by npostman** [comment]
No worries and makes sense. If you want, you can leave this PR open for now and I will see if I can add some test coverage at some point.

**Comment by dwightwatson** [comment]
Reviewing the `composer.json` file now - there actually isn't anything that prevents it from being installed on current PHP/Laravel versions - all the version constraints are `>=` so it's super flexible. I was able to install it into a current PHP 8.0/Laravel 8.43.0 project right now.

I think if you need the additional stuff you're better off putting this directly into your app or using your fork - I'm not using this package anymore and unlikely to keep maintaining it I'm afraid.

**Comment by npostman** [comment]
Roger that. I'll close this PR then.

**Pull request closed without merging**
